language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  fqdn: prototypical.pro
  on:
    branch: master
branches:
  only:
    - master
    - /^greenkeeper.*$/